Repository zonemaster/zonemaster-cli, pull requests merged in 2020-10, with the labels that each got.

#157 Related to zonemaster-engine issue 578
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
Labels: A-Code

#167 Corrected listing of files
  share/Makefile
Labels: A-BuildSystem

#168 Updated MANIFEST.SKIP
  MANIFEST.SKIP
Labels: A-BuildSystem, P-High

#169 Fix make and makefile
  .gitignore
  MANIFEST
  Makefile.PL
  docs/Installation.md
  share/GNUmakefile
  share/Makefile
Labels: A-BuildSystem, P-High, T-Bug

#172 Fix typo
  docs/Installation.md
Labels: A-Documentation

#173 Prepare PO files for translation
  share/GNUmakefile
  share/da.po
  share/fr.po
  share/sv.po
Labels: A-Translation
