Repository zonemaster/zonemaster-cli, pull requests merged in 2021-12, with the labels that each got.

#230 Updates Finnish translation (CLI)
  share/fi.po
Labels: A-Translation

#234 Preparation for release v2021.2 (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High

#235 Merge develop into master
  Changes
  Dockerfile
  LICENSE
  MANIFEST.SKIP
  Makefile.PL
  README.md
  USING.md
  docs/Installation.md
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
  share/GNUmakefile
  share/fi.po
  share/nb.po
  share/sv.po
  share/update-po
Labels: P-High

#237 Updates French tranlation
  share/fr.po
Labels: A-Translation

#236 Update danish translation
  share/da.po
Labels: A-Translation

#238 Clarifies IPv6 limitations
  USING.md
Labels: A-Documentation

#219 New translation to spanish language.
  MANIFEST
  share/es.po
Labels: A-Translation

#239 Preparation for v2021.2.1 release (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High

#240 Merge develop into master (CLI)
  Changes
  MANIFEST
  Makefile.PL
  USING.md
  lib/Zonemaster/CLI.pm
  share/da.po
  share/es.po
  share/fr.po
Labels: P-High

#243 Missing Spanish locale in Installation document
  docs/Installation.md
Labels: T-Bug, A-Documentation
