Repository zonemaster/zonemaster-cli, pull requests merged in 2021-01, with the labels that each got.

#183 Resolves issue where selected profile overrides IPv4/6 setting in CLI
  lib/Zonemaster/CLI.pm
Labels: A-Code, T-Bug

#110 Fix for --sourceaddr bad behaviour
  .travis.yml
  Makefile.PL
  docs/Installation.md
  lib/Zonemaster/CLI.pm
  share/fr.po
  share/sv.po
Labels: P-High

#185 Updates the ipv4 and ipv6 command line options
  lib/Zonemaster/CLI.pm
Labels: A-Code, P-High

#186 Avoid updating PO files for clean repo
  Makefile.PL
Labels: A-Translation, T-Bug

#188 Update dependencies installation on CentOS
  docs/Installation.md
Labels: A-Installation, P-High
