Repository zonemaster/zonemaster-cli, pull requests merged in 2022-05, with the labels that each got.

#255 Update IDN support warning message
  lib/Zonemaster/CLI.pm
  share/fr.po
Labels: A-Translation

#268 use pre-built packages for ubuntu
  docs/Installation.md
Labels: P-High, A-Documentation

#269 Updates Finnish translation (CLI)
  share/fi.po
Labels: A-Translation

#266 Updated and added Norwegian language translations.
  share/nb.po
Labels: P-High, A-Translation

#267 Update spanish translation file for upcoming release, ticket #263
  share/es.po
Labels: P-High, A-Translation
