Repository zonemaster/zonemaster-cli, pull requests merged in 2022-07, with the labels that each got.

#271 Update danish translation
  share/da.po
Labels: P-High, A-Translation

#275 Adds missing installation instructions for CentOS Linux 7 (CLI)
  docs/Installation.md
Labels: P-High, A-Documentation

#276 Preparation for v2022.1.1 (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High

#278 Fixes error in PO file that prevents MO to be created
  share/da.po
Labels: T-Bug
