Repository zonemaster/zonemaster-cli, pull requests merged in 2023-02, with the labels that each got.

#304 Provide a rule "new-po" to create an empty PO file
  share/GNUmakefile
Labels: V-Patch

#306 Zonemaster::LDNS and libldns versions
  lib/Zonemaster/CLI.pm
Labels: T-Feature, V-Major

#308 Make `--[no-]show-...` options work with JSON output
  lib/Zonemaster/CLI.pm
Labels: V-Major

#303 Update translations and po files (CLI)
  share/da.po
  share/es.po
  share/fi.po
  share/fr.po
  share/nb.po
  share/sv.po
Labels: A-Translation, V-Patch
