Repository zonemaster/zonemaster-cli, pull requests merged in 2023-07, with the labels that each got.

#342 Update of the Norwegian translation ref. issue #324
  share/nb.po
Labels: A-Translation, V-Patch

#344 Preparation for release v2023.1.1 (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High, V-Patch

#346 Merge Releases/v2023.1.1 into Master (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
  share/nb.po
Labels: P-High
