Repository zonemaster/zonemaster-cli, pull requests merged in 2023-06, with the labels that each got.

#337 Fix option --[no-]json-translate
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
Labels: T-Bug, P-High, V-Patch

#328 Updates Swedish translation (CLI)
  share/sv.po
Labels: A-Translation, V-Patch

#338 Updates Danish translation (CLI)
  share/da.po
Labels: A-Translation, V-Patch

#339 Preparation for release v2023.1 (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High
