Repository zonemaster/zonemaster-cli, pull requests merged in 2023-03, with the labels that each got.

#311 Preparation release v2022.2.2 (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High

#309 Improve implementation for JSON and raw options
  lib/Zonemaster/CLI.pm
Labels: V-Major

#320 Remove PO tests from distribution package
  MANIFEST
  MANIFEST.SKIP
Labels: T-Bug, P-High

#317 New options "--sourceaddr4" and "--sourceaddr6"
  lib/Zonemaster/CLI.pm
Labels: V-Minor
