Repository zonemaster/zonemaster-cli, pull requests merged in 2023-05, with the labels that each got.

#327 Update French translation for v2023.1 release
  share/fr.po
Labels: A-Translation, V-Patch

#332 Remove documentation (moved to zonemaster/zonemaster)
  MANIFEST
  README.md
  USING.md
  docs/Installation.md
Labels: A-Documentation

#329 Update spanish translation as requested in issue #322
  share/es.po
Labels: A-Translation, V-Patch

#335 Fix table layout
  lib/Zonemaster/CLI.pm
Labels: T-Bug, V-Patch
