Repository zonemaster/zonemaster-cli, pull requests merged in 2024-11, with the labels that each got.

#393 Fix locale spelling
  t/usage.t
Labels: V-Patch

#391 Disable failing tests for now
  t/usage.t
Labels: V-Patch

#371 Make usage documentation consistent and also demoose
  .travis.yml
  Dockerfile
  MANIFEST
  Makefile.PL
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
  t/pod.t
  t/usage.t
  t/usage.wrapper.pl
Labels: V-Patch

#395 Make --stop-level disabled by default again
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
  t/usage.normal.data
  t/usage.t
Labels: P-High, V-Minor

#389 Organize --help text
  README.md
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
Labels: V-Patch

#398 Corrects gettext code and adds dependency required by CI (Travis)
  .travis.yml
  lib/Zonemaster/CLI.pm
  t/usage.t
Labels: T-Bug, P-High, V-Patch

#399 Cleanup of .travis.yml
  .travis.yml
Labels: V-Patch
