Repository zonemaster/zonemaster-cli, pull requests merged in 2024-10, with the labels that each got.

#386 Improved test coverage
  Makefile.PL
  lib/Zonemaster/CLI.pm
  script/zonemaster-cli
  t/usage.t
Labels: V-Patch

#383 Check MANIFEST when PR is created
  MANIFEST.SKIP
  t/manifest.t
Labels: S-PRforIssue

#382 Fixing errors display when using options '--ns' or '--ds'
  lib/Zonemaster/CLI.pm
Labels: V-Minor
