Repository zonemaster/zonemaster-cli, pull requests merged in 2025-02, with the labels that each got.

#416 Zonemaster::CLI: don’t lose early log messages
  lib/Zonemaster/CLI.pm
Labels: T-Bug, V-Patch

#415 Updated spanish translation
  share/es.po
Labels: A-Translation, V-Patch

#384 Adds translation to Slovenian
  MANIFEST
  share/sl.po
Labels: A-Translation

#418 Danish translation (cli)
  share/da.po
Labels: A-Translation
