Repository zonemaster/zonemaster-cli, pull requests merged in 2025-06, with the labels that each got.

#359 More flexible --test option
  MANIFEST
  lib/Zonemaster/CLI.pm
  lib/Zonemaster/CLI/TestCaseSet.pm
  script/zonemaster-cli
  t/test_case_set.t
  t/usage.t
Labels: V-Major

#437 Updates Perl version in CI (CLI)
  .github/workflows/ci.yml
Labels: P-High, V-Patch

#446 Preparation for v2025.1 release (CLI)
  Changes
  Makefile.PL
  lib/Zonemaster/CLI.pm
Labels: P-High
